logo: images/ferris-climbing.png
title: An RRB-Tree based vector for Rust
description: A confluently persistent vector implementation for Rust based on RRB-Tree
theme: jekyll-theme-minimal
exclude:
  - Cargo.toml
  - Cargo.lock
  - Gemfile
  - Gemfile.lock
  - src
  - benches
  - benches-mem
  - tests
  - web-vis
  - reports
  - wrangler.jsonc
