name: build
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.42.0
          components: rustfmt, clippy
      - name: Checking code style
        run: cargo fmt --all -- --check
      - name: Running unit tests for the large branching factor
        run: cargo test --all
      - name: Running unit tests for the small branching factor
        run: cargo test --all --features "small_branch"
      - name: Running benchmarks as tests
        run: cargo test --benches
      - name: Running memory benchmarks as tests
        run: sh bench.sh
        working-directory: benches-mem
