name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build_rust:
    name: Build and validate Rust bits
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68.1
          components: rustfmt, clippy
      - name: Checking code style
        run: cargo fmt --all -- --check
      - name: Running unit tests for the large branching factor
        run: cargo test --all
      - name: Running unit tests for the small branching factor
        run: cargo test --all --features "small_branch"
      - name: Running benchmarks as tests
        run: cargo test --benches
      - name: Running memory benchmarks as tests
        run: sh bench.sh
        working-directory: benches-mem

  build_js:
    name: Build and validate JS bits
    runs-on: macos-latest

    defaults:
      run:
        working-directory: web-vis/www/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies
        run: npm install
      - name: Checking code style
        run: npx prettier --check .
